// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SpringOMeterSquareline

#include "ui.h"

void test_function(lv_event_t * e)
{
	// Your code here
}
