// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SpringOMeterSquareline

#include "../ui.h"

// COMPONENT ButtonNav

lv_obj_t * ui_ButtonNav_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ButtonNav;
    cui_ButtonNav = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_ButtonNav, lv_pct(30));
    lv_obj_set_height(cui_ButtonNav, lv_pct(15));
    lv_obj_set_x(cui_ButtonNav, 1);
    lv_obj_set_y(cui_ButtonNav, -81);
    lv_obj_set_align(cui_ButtonNav, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ButtonNav, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_ButtonNav, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTONNAV_NUM);
    children[UI_COMP_BUTTONNAV_BUTTONNAV] = cui_ButtonNav;
    lv_obj_add_event_cb(cui_ButtonNav, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ButtonNav, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ButtonNav_create_hook(cui_ButtonNav);
    return cui_ButtonNav;
}

