// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SpringOMeterSquareline

#ifndef _UI_COMP_BUTTONNAV_H
#define _UI_COMP_BUTTONNAV_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ButtonNav
#define UI_COMP_BUTTONNAV_BUTTONNAV 0
#define _UI_COMP_BUTTONNAV_NUM 1
lv_obj_t * ui_ButtonNav_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
