// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SpringOMeterSquareline

#ifndef _SPRINGOMETERSQUARELINE_UI_COMP_HOOK_H
#define _SPRINGOMETERSQUARELINE_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_ButtonNav_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
