// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SpringOMeterSquareline

#include "../ui.h"

lv_obj_t * uic_HomeScreen;
lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_ButtonNav = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Setup, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Setup_screen_init);
    }
}

void ui_event_ButtonNav_ButtonNav(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        test_function(e);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_Button2, lv_pct(30));
    lv_obj_set_height(ui_Button2, lv_pct(15));
    lv_obj_set_x(ui_Button2, -108);
    lv_obj_set_y(ui_Button2, -79);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_Button1, lv_pct(30));
    lv_obj_set_height(ui_Button1, lv_pct(15));
    lv_obj_set_x(ui_Button1, 108);
    lv_obj_set_y(ui_Button1, -81);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonNav = ui_ButtonNav_create(ui_Home);
    lv_obj_set_x(ui_ButtonNav, 1);
    lv_obj_set_y(ui_ButtonNav, -81);

    ui_Label2 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -111);
    lv_obj_set_y(ui_Label2, -80);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Setup");

    ui_Label3 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, -81);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Trial");

    ui_Label4 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 104);
    lv_obj_set_y(ui_Label4, -82);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Result");

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonNav, ui_event_ButtonNav_ButtonNav, LV_EVENT_ALL, NULL);
    uic_HomeScreen = ui_Home;

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    uic_HomeScreen = NULL;
    ui_Home = NULL;
    ui_Button2 = NULL;
    ui_Button1 = NULL;
    ui_ButtonNav = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;

}
