// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SpringOMeterSquareline

#include "../ui.h"

lv_obj_t * uic_SetupScreen;
lv_obj_t * ui_Setup = NULL;
lv_obj_t * ui_ButtonNav1 = NULL;
// event funtions
void ui_event_ButtonNav1_ButtonNav(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
    }
}

// build funtions

void ui_Setup_screen_init(void)
{
    ui_Setup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonNav1 = ui_ButtonNav_create(ui_Setup);
    lv_obj_set_x(ui_ButtonNav1, -107);
    lv_obj_set_y(ui_ButtonNav1, -86);

    lv_obj_add_event_cb(ui_ButtonNav1, ui_event_ButtonNav1_ButtonNav, LV_EVENT_ALL, NULL);
    uic_SetupScreen = ui_Setup;

}

void ui_Setup_screen_destroy(void)
{
    if(ui_Setup) lv_obj_del(ui_Setup);

    // NULL screen variables
    uic_SetupScreen = NULL;
    ui_Setup = NULL;
    ui_ButtonNav1 = NULL;

}
