// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SpringOMeterSquareline

#ifndef UI_SETUP_H
#define UI_SETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Setup
extern void ui_Setup_screen_init(void);
extern void ui_Setup_screen_destroy(void);
extern lv_obj_t * ui_Setup;
extern void ui_event_ButtonNav1_ButtonNav(lv_event_t * e);
extern lv_obj_t * ui_ButtonNav1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SetupScreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

