// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SpringOMeterSquareline

#include "../ui.h"

lv_obj_t * uic_TrialScren;
lv_obj_t * ui_Trial = NULL;
// event funtions

// build funtions

void ui_Trial_screen_init(void)
{
    ui_Trial = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Trial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_TrialScren = ui_Trial;

}

void ui_Trial_screen_destroy(void)
{
    if(ui_Trial) lv_obj_del(ui_Trial);

    // NULL screen variables
    uic_TrialScren = NULL;
    ui_Trial = NULL;

}
