// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SpringOMeterSquareline

#ifndef UI_TRIAL_H
#define UI_TRIAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Trial
extern void ui_Trial_screen_init(void);
extern void ui_Trial_screen_destroy(void);
extern lv_obj_t * ui_Trial;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TrialScren;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

